#!/usr/bin/env ruby

POLLING_INTERVAL = 30 # sec
IDLENESS_THRESHOLD = 2 * POLLING_INTERVAL * 1000 # msec

def current_window
  `xdotool getactivewindow getwindowname`
end

def idle_time
  `xprintidle`.to_i(10)
end

def idle?
  idle_time > IDLENESS_THRESHOLD
end

last_state = nil

loop do
  if idle?
    state = "idle"
  else
    state = current_window
  end
  if state != last_state
    $stdout.puts "%s %s" % [Time.now.strftime("%Y-%m-%d %H:%M"), state]
    $stdout.flush
    last_state = state
  end
  sleep POLLING_INTERVAL
end
